PratamaApp/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\bookController;
use App\Http\Controllers\memberController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::resource('books', bookController::class);

Route::resource('members', memberController::class);

PratamaApp/app/Models/book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class book extends Model
{
    use HasFactory;
    protected $fillable = ['kode_buku', 'judul_buku', 'penerbit_buku', 'pengarang_buku', 'jumlah_buku'];
}

PratamaApp/app/Http/Controllers/bookController.php
<?php

namespace App\Http\Controllers;

use App\Models\book;
use Illuminate\Http\Request;

class bookController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $books = book::all();
        return view('books.index', ['books' => $books]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('books.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //validasi
        $validated = $request->validate([
            'kode_buku' => 'required',
            'judul_buku' => 'required',
            'penerbit_buku' => 'required',
            'pengarang_buku' => 'required',
            'jumlah_buku' => 'required|integer|min:1',
        ]);

        //simpan ke database
        $book = book::create([
            'kode_buku' => $request->input ('kode_buku'),
            'judul_buku' => $request->input ('judul_buku'),
            'penerbit_buku' => $request->input ('penerbit_buku'),
            'pengarang_buku' => $request->input ('pengarang_buku'),
            'jumlah_buku' => $request->input ('jumlah_buku'),


        ]);

        //flash message
        if($book){
            return redirect()->route('books.index')->with('success','Buku Berhasil Disimpan');
        }
        else{
            return redirect()->back()->with('error','Buku Gagal Disimpan');
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(book $book)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $book = book::find($id);

        return view('books.edit', ['book' => $book]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Book $book){
        $validated = $request->validate([
            'kode_buku' => 'required',
            'judul_buku' => 'required',
            'penerbit_buku' => 'required',
            'pengarang_buku' => 'required',
            'jumlah_buku' => 'required|integer|min:0',
        ]);

        $book->update([
            'kode_buku' => $request->input('kode_buku'),
            'judul_buku' => $request->input('judul_buku'),
            'penerbit_buku' => $request->input('penerbit_buku'),
            'pengarang_buku' => $request->input('pengarang_buku'),
            'jumlah_buku' => $request->input('jumlah_buku'),
        ]);

        if ($book) {
            return redirect()->route('books.index')->with('success', 'Data Berhasil Diperbarui');
        } else {
            return redirect()->back()->with('error', 'Data Gagal Diperbarui');
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
    
        $books = book::destroy($id);
        $books = book::all();   
        return view('books.index', ['books' => $books]);
    }

    
}

PratamaApp/resources/views/books/create.blade.php
@include('layout/header', ['title' => 'Form Data Buku'])  
    <div class="container pt-4 bg-white"> 

        <h2>Form Data Buku</h2> 
        @include('flash-message')
        <form action="{{ route('books.store') }}" method="post"> 
            @csrf 

        <div class="mb-3">
            <label class="form-label">Kode Buku</label>
            <input type="text" class="form-control" name="kode_buku">
        </div>
        <div class="mb-3">
            <label class="form-label">Judul Buku</label>
            <input type="text" class="form-control" name="judul_buku">
        </div>
        <div class="mb-3">
            <label class="form-label">Penerbit Buku</label>
            <input type="text" class="form-control" name="penerbit_buku">
        </div>
        <div class="mb-3">
            <label class="form-label">Pengarang Buku</label>
            <input type="text" class="form-control" name="pengarang_buku">
        </div>
        <div class="mb-3">
            <label class="form-label">Jumlah Buku</label>
            <input type="text" class="form-control" name="jumlah_buku">
        </div>
        <button type="submit" class="btn btn-primary">Simpan</button>
        </form>
    </div>
    
@include('layout/footer')

PratamaApp/resources/views/books/edit.blade.php
@include('layout/header', ['title' => 'Edit Data Buku'])   
    <div class="container pt-4 bg-white"> 

        <h2>Edit Data Buku</h2> 
        @include('flash-message')

        <form action="{{ route('books.update' , $book->id) }}" method="post"> 
            @csrf 
            @method('PUT')

        <div class="mb-3">
            <label class="form-label">Kode Buku</label>
            <input type="text" class="form-control" name="kode_buku" value="{{ $book->kode_buku }}" readonly>
        </div>
        <div class="mb-3">
            <label class="form-label">Judul Buku</label>
            <input type="text" class="form-control" name="judul_buku" value="{{ $book->judul_buku }}">
        </div>
        <div class="mb-3">
            <label class="form-label">Penerbit Buku</label>
            <input type="text" class="form-control" name="penerbit_buku" value="{{ $book->penerbit_buku }}">
        </div>
        <div class="mb-3">
            <label class="form-label">Pengarang Buku</label>
            <input type="text" class="form-control" name="pengarang_buku" value="{{ $book->pengarang_buku }}">
        </div>
        <div class="mb-3">
            <label class="form-label">Jumlah Buku</label>
            <input type="text" class="form-control" name="jumlah_buku" value="{{ $book->jumlah_buku }}">
        </div>
        <td>
        <button type="submit" class="btn btn-primary">Simpan</button>
        <button type="reset" class="btn btn-primary"> Reset </button>
        </td>
        </form>
    </div>

@include('layout/footer')

PratamaApp/resources/views/books/index.blade.php
@include('layout/header', ['title' => 'Data buku'])   
<div class="container pt-4 bg-white">
    
        <h2>Data Buku Perpustakaan</h2>
        <a href = "{{route('books.create')}}" class="btn btn-info">Create</a>
        @include('flash-message')
                
        <table class="table table-hover">
            <tr>
                <th>Kode Buku</th>
                <th>Judul</th>
                <th>Penerbit</th>
                <th>Pengarang</th>
                <th>Jumlah</th>
                <th>Action</th>
            </tr>
            @foreach ($books as $book )   
                <tr>
                    <td>{{ $book->kode_buku }}</td>
                    <td>{{ $book->judul_buku }}</td>
                    <td>{{ $book->penerbit_buku }}</td>
                    <td>{{ $book->pengarang_buku }}</td>
                    <td>{{ $book->jumlah_buku }}</td>
                    <td>
                        <div class="btn-group" role="group" aria-label="Basic example">
                        <form action="{{ route('books.destroy', [$book]) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <a href="{{ route('books.edit', [$book]) }}" class="btn btn-primary">Edit</a>
                            <button class="btn btn-primary">Delete</button>
                        </form>
                        </div>
                    </td>
                </tr>
            @endforeach
        </table>
</div>
@include('layout/footer')